// Copyright (c) ZeniMax Media Inc.
// Licensed under the GNU General Public License 2.0.
// G:\quake2\xpack\models/monsters/turret

// This file generated by qdata - Do NOT Modify

enum
{
	FRAME_stand01,
	FRAME_stand02,
	FRAME_active01,
	FRAME_active02,
	FRAME_active03,
	FRAME_active04,
	FRAME_active05,
	FRAME_active06,
	FRAME_run01,
	FRAME_run02,
	FRAME_pow01,
	FRAME_pow02,
	FRAME_pow03,
	FRAME_pow04,
	FRAME_death01,
	FRAME_death02
};

constexpr float MODEL_SCALE = 3.500000f;
